repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ["-L", "te,ser,nd,ot", "-w"]
        files: "\\.(tex|bib)$"
  - repo: https://github.com/itsjoesullivan/chktex-pre-commit
    rev: v1.0.0
    hooks:
      - id: chktex
        args: ["-q", "-n1", "-n8", "-n36"]
        files: "\\.(tex)$"
