name: LCI Auto Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Run data integration
      run: |
        source .venv/bin/activate
        python src/data_integration.py || echo "Integration failed, continuing with fallback"

    - name: Run main pipeline
      run: |
        source .venv/bin/activate
        python src/lci_program.py
        python src/make_ipd.py
        python src/figures.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lci-results
        path: |
          results/tables/
          results/figures/
