name: LCI Full Build (PDF + Results)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Run pipeline
      run: |
        source .venv/bin/activate
        python src/data_integration.py || echo "Integration skipped"
        python src/lci_program.py
        python src/make_ipd.py
        python src/figures.py

    - name: Install LaTeX
      run: sudo apt-get update && sudo apt-get install -y texlive-full latexmk

    - name: Build paper PDF
      run: |
        latexmk -pdf -interaction=nonstopmode -halt-on-error paper.tex
        mkdir -p results/pdf
        mv paper.pdf results/pdf/lci_paper_build.pdf

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: lci-full-artifacts
        path: |
          results/tables/
          results/figures/
          results/pdf/
