name: LCI Full Build (PDF + Results)

on:
  workflow_dispatch:

jobs:
  full:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Generate demo results (strict)
        run: |
          set -e
          python src/lci_program.py
          test -f results/tables/lci_by_family.csv || (echo "Missing lci_by_family.csv" && exit 1)
          test -f results/tables/ipd.csv || (echo "Missing ipd.csv" && exit 1)

      - name: Build paper
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends texlive-latex-extra texlive-fonts-recommended texlive-science latexmk
          if [ -f paper/main.tex ]; then
            (cd paper && latexmk -pdf -halt-on-error -interaction=nonstopmode main.tex)
          else
            echo "No paper/main.tex found; skipping TeX build."
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lci-full
          path: |
            results/**
            paper/*.pdf
          if-no-files-found: warn